---
version: 2

models:
  - name: latest_failed_models_v2
    description: |
      The list of the latest failed models each.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - invocation_id
            - unique_id

    columns:
      - name: unique_id
        description: "unique test ID"
        tests:
          - not_null
