name: dbt_artifacts_models

profile: dbt-artifacts-loader

version: '1.0'
config-version: 2
require-dbt-version: ">=0.19.0"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

vars:
    dbt_artifacts_loader:
        project: "ubie-yu-sandbox"
        dataset: "dbt_artifacts"
