---
version: 2

models:
  - name: last_schema_test_run_results_v2
    description: |
      The table contains only the latest record of schema test run results v2.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - run_results_metadata.invocation_id
            - unique_id
            - timing_name

    columns:
      - name: run_results_metadata.invocation_id
        description: "invocation ID"
        tests:
          - not_null
      - name: unique_id
        description: "unique test ID"
        tests:
          - not_null
          - unique
      - name: timing_name
        description: "timing name"
        tests:
          - accepted_values:
              values: ["execute"]
