---
version: 2

models:
  - name: parsed_model_node_v4
    description: |
      This is a table to expand `manifest_v4.node.value.ParsedModelNode`.
      The table exclude duplicates.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - metadata.invocation_id
            - unique_id

    columns:
      - name: metadata.invocation_id
        description: "invocation ID"
        tests:
          - not_null
      - name: unique_id
        description: "unique ID"
        tests:
          - not_null
