# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile
config:
  partial_parse: False
  send_anonymous_usage_stats: False

dbt-artifacts-loader:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "ubie-jp-data-engineering-qa"
      location: "asia-northeast1"
      dataset: "dbt_artifacts"
      priority: "{{ env_var('DBT_BIGQUERY_PRIORITY', 'interactive') }}"
      threads: |
        {{ env_var("DBT_THREADS", 20) }}
