---
version: 2

models:
  - name: data_test_run_results_v2
    description: |
      This is a denormalized data test run results v2.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - run_results_metadata.invocation_id
            - unique_id
            - timing_name

    columns:
      - name: run_results_metadata.invocation_id
        description: "invocation ID"
        tests:
          - not_null
      - name: unique_id
        description: "unique test ID"
        tests:
          - not_null
