---
version: 2

models:
  - name: model_run_results_v2
    description: |
      This is a denormalized model run results v2.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - metadata.invocation_id
            - unique_id
            - timing_name

    columns:
      - name: metadata.invocation_id
        description: "invocation ID"
        tests:
          - not_null
      - name: unique_id
        description: "unique test ID"
        tests:
          - not_null
      - name: timing_name
        description: "timing name"
        tests:
          - accepted_values:
              values: ["execute"]
