---
version: 2

models:
  - name: latest_run_results_v2
    description: |
      The records means the latest run results on the 'run_results_v2' table.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - invocation_id
            - unique_id

    columns:
      - name: unique_id
        description: "unique test ID"
        tests:
          - not_null
