---
version: 2

models:
  - name: latest_failed_tests_v1
    description: |
      The list of the latest failed tests each.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - invocation_id
            - unique_id

    columns:
      - name: unique_id
        description: "unique test ID"
        tests:
          - not_null
