name: Checks in a Pull Request

on:
  push:

jobs:

  python:
    strategy:
      matrix:
        include:
          - python_version: 3.8
          - python_version: 3.9
          - python_version: 3.10

    runs-on: ubuntu-20.04
    env:
      ENV_FILE: ".env/.env.test"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - name: install dependencies
        run: |
          bash ci/setup.sh
      - name: lint
        run: |
          bash ci/lint_python.sh
      - name: test
        run: |
          export ENV_FILE="${{ env.ENV_FILE }}"
          bash ci/run_python_tests.sh
