name: Push the docker image to Docker Hub

on:
  release:
    types:
      - published

env:
  DOCKER_IMAGE_BASE: "yuiskw/dbt-artifacts-loader"

jobs:
  set-release-tag-name:
    runs-on: ubuntu-latest
    outputs:
      release_tag_name: ${{ steps.set-release-tag-name.outputs.release_tag_name }}
    steps:
      - name: Set release tag name
        id: set-release-tag-name
        run: |
          release_tag_name="${{ github.event.release.tag_name }}"
          echo "::set-output name=release_tag_name::${release_tag_name}"

  push:
    needs: ["set-release-tag-name"]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build a docker image
        run: |
          release_tag_name="${{needs.set-release-tag-name.outputs.release_tag_name}}"
          docker_image="${{ env.DOCKER_IMAGE_BASE }}:${release_tag_name}"
          bash ci/build_docker.sh "$docker_image"
      - name: Push the docker image
        run: |
          release_tag_name="${{needs.set-release-tag-name.outputs.release_tag_name}}"
          docker_image="${{ env.DOCKER_IMAGE_BASE }}:${release_tag_name}"
          docker push "$docker_image"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
